export const variables = {
    active_page: "strona_glowna",
    towary: [],
    dodaj_towar: false,
    jednostki_towarowe: ["szt.", "kWh", "ml"],
    edytuj_towar: false,
    dodaj_transakcje: false,
    towary_temporary_array: [],
    towar_index: 0,
    suma_wydatkow: 0,
    dochod: 0,
    temp_wydatek: 0,
    temp_przychod: 0,
    temp_dochod: 0,
    temp_date: '',
    transakcje: [],
    edycja_transakcji: false,
    numer_edytowanej_transakcji: 0,
    rok_transakcji: 0,
    miesiac_transakcji: 0,
    towary_dane: []
}